export type ModelProvider =
  | "openai"
  | "google"
  | "anthropic"
  | "mistral"
  | "groq"
  | "perplexity"
  | "ollama"
  | "openrouter"
  | "custom"

export type DietProvider =
  | "none"
  | "mediterranean"
  | "vegan"
  | "vegetarian"
  | "paleo"
  | "keto"
  | "low-carb"
  | "gluten-free"
  | "ketogenic"
